# environment.yml
name: resilience-atlas
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pandas=2.1
  - numpy=1.24
  - scipy=1.11
  - scikit-learn=1.3
  - statsmodels=0.14   # For econometric models
  - matplotlib=3.8
  - seaborn=0.13
  - plotly=5.17
  - geopandas=0.14
  - xarray=2023.12     # For climate data
  - netCDF4=1.6
  - cdsapi=0.6         # For ECMWF downloads
  - dask=2023.12       # For large data processing
  - jupyter=1.0
  - pytest=7.4
  - black=23.12        # Code formatting
  - ruff=0.1           # Linting
  - pre-commit=3.5
